name: Test

on:
  push:
    branches:
    - master
    - develop
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  functional:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Ape
      uses: ApeWorX/github-action@v1

    - name: Setup anvil
      # TODO: Skip if already downloaded
      run: curl -L https://foundry.paradigm.xyz | bash
      # TODO: Cache foundry binaries

    - name: Upgrade anvil
      run: foundryup

    - name: Compile Code
      run: ape compile --size

    - name: Run Tests
      run: ape test tests/functional -s --gas
